# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eajni
brief-intro: IT 초보사전 💦💦
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eajni.github.io" # the base hostname & protocol for your site

permalink: /:categories/:title/

# other links
github_username: eajni
email: eajni.h@gmail.com

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname:
disqus_shortname:

# statistic analysis
google_analytics_id:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      plantuml: _includes/plantuml.html

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-plantuml, jekyll-paginate]
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-plantuml
